package com.jeanhilger.inventory.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.jeanhilger.inventory.repository.UserRepository;

@Controller
@RequestMapping(path="/user")
public class UserController {
	// This means to get the bean called userRepository
    // Which is auto-generated by Spring
	@Autowired
	private UserRepository userRepository;

}
